### ISSUE TITLE
Task 'compileJava' not found in project ':game'

### ISSUE THREAD

**Issue by BlizzedRu** [littlektframework/littlekt-game-template#3]
Hi! 
First of all I'm very thankful for this library, great job!

After cloning the template project and trying to run jvm App I got such error:
`Task 'compileJava' not found in project ':game'`

Gradle JVM is set, other tasks work great. Running this task (or `compileKotlin`) manually fails with `There is no feature named VERSION_CATALOGS`

**Comment by LeHaine** [comment]
Which tasks are you running specifically to run the JVM app? Are you using an IDE or the Gradle CLI? I am able to run it fine directly through IntellIJ with the following run configuration:

![image](https://user-images.githubusercontent.com/4951150/224494291-e1c9b0ea-3c17-44a7-9d9e-b9a157921312.png)

**Comment by BlizzedRu** [comment]
In the IDE in the same way and options
Okay, thank you for your help. It seems that this problem is on my side
Thank you!
